# Generated by Django 2.0.5 on 2018-05-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhistoryuser',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoryUser',
        ),
        migrations.DeleteModel(
            name='HistoricalHistoryUser',
        ),
        migrations.DeleteModel(
            name='HistoricalProfile',
        ),
    ]
