# Generated by Django 2.0.5 on 2018-06-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180531_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_review_certificates', 'Can Review all Certificates'), ('can_adjudicate_edit_requests', 'Can Adjudicate Edit Requests'))},
        ),
    ]
