# Generated by Django 2.0.5 on 2018-06-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180608_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_review_certificates', 'Can Review all Certificates'), ('can_approve_or_reject_edit_requests', 'Can Approve/Reject Certificate Edit Requests'))},
        ),
    ]
