# Generated by Django 2.0.4 on 2018-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0003_auto_20180416_2036'),
        ('accounts', '0003_auto_20180412_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='licensees',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='kpc.Licensee'),
        ),
    ]
