# Generated by Django 2.0.5 on 2018-05-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_licensees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_review_certificates', 'Can Review all Certificates'),)},
        ),
    ]
