# Generated by Django 2.0.4 on 2018-04-06 20:10

import django.core.validators
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('primary_contact', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=1024)),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address continued')),
                ('city', models.CharField(max_length=1024)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('tax_id', models.CharField(help_text='Tax Identification Number', max_length=10, validators=[django.core.validators.RegexValidator(message='TIN format: ##-#######', regex='\\d{2}-\\d{7}')])),
            ],
        ),
    ]
