# Generated by Django 2.0.4 on 2018-04-12 18:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLicensee',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('primary_contact', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=1024)),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address continued')),
                ('city', models.CharField(max_length=1024)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('tax_id', models.CharField(help_text='Tax Identification Number', max_length=10, validators=[django.core.validators.RegexValidator(message='TIN format: ##-#######', regex='\\d{2}-\\d{7}')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical licensee',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
