# Generated by Django 2.0.5 on 2018-06-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0002_auto_20180604_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateconfig',
            name='reviewer_emails',
        ),
        migrations.RemoveField(
            model_name='historicalcertificateconfig',
            name='reviewer_emails',
        ),
    ]
