# Generated by Django 2.0.4 on 2018-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0002_historicallicensee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallicensee',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='licensee',
            name='primary_contact',
        ),
    ]
