# Generated by Django 2.0.5 on 2018-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0003_auto_20180531_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateconfig',
            name='edit_requests',
            field=models.BooleanField(default=False, help_text='If True, users will be able to submit a request to modify a prepared certificate.', verbose_name='Certificate Edit Requests'),
        ),
        migrations.AddField(
            model_name='historicalcertificateconfig',
            name='edit_requests',
            field=models.BooleanField(default=False, help_text='If True, users will be able to submit a request to modify a prepared certificate.', verbose_name='Certificate Edit Requests'),
        ),
    ]
