# Generated by Django 2.0.4 on 2018-04-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0004_auto_20180416_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='shipped_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value in USD', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='void',
            field=models.BooleanField(default=False, help_text='Certificate has been voided?'),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='shipped_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value in USD', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='void',
            field=models.BooleanField(default=False, help_text='Certificate has been voided?'),
        ),
    ]
