# Generated by Django 2.0.4 on 2018-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0005_auto_20180417_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhscode',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='harmonized_code',
            field=models.CharField(blank=True, choices=[('7102.10', '7102.10'), ('7102.21', '7102.21'), ('7102.29', '7102.29'), ('7102.31', '7102.31'), ('7102.39', '7102.39')], default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('prepared', 'Prepared'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('void', 'Void')], default='assigned', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='harmonized_code',
            field=models.CharField(blank=True, choices=[('7102.10', '7102.10'), ('7102.21', '7102.21'), ('7102.29', '7102.29'), ('7102.31', '7102.31'), ('7102.39', '7102.39')], default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check')], default='cash', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('prepared', 'Prepared'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('void', 'Void')], default='assigned', max_length=16),
        ),
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
        migrations.DeleteModel(
            name='HistoricalHSCode',
        ),
        migrations.DeleteModel(
            name='HSCode',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
