# Generated by Django 2.0.4 on 2018-04-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0007_auto_20180418_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Prepared'), (2, 'In-transit'), (3, 'Delivered'), (4, 'Void')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Prepared'), (2, 'In-transit'), (3, 'Delivered'), (4, 'Void')], default=0),
        ),
    ]
