# Generated by Django 2.0.4 on 2018-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0009_auto_20180425_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='attested',
            field=models.BooleanField(default=False, help_text='I have completed the necessary\n                                                                application pertaining to this shipment,\n                                                                including the warranty that the diamonds\n                                                                being shipped were not traded to fund conflict.'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='attested',
            field=models.BooleanField(default=False, help_text='I have completed the necessary\n                                                                application pertaining to this shipment,\n                                                                including the warranty that the diamonds\n                                                                being shipped were not traded to fund conflict.'),
        ),
    ]
