# Generated by Django 2.0.4 on 2018-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0010_auto_20180426_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date_of_delivery',
            field=models.DateField(blank=True, help_text='Date certificate was marked DELIVERED', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='date_of_shipment',
            field=models.DateField(blank=True, help_text='Date certificate was marked IN TRANSIT', null=True),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='date_of_delivery',
            field=models.DateField(blank=True, help_text='Date certificate was marked DELIVERED', null=True),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='date_of_shipment',
            field=models.DateField(blank=True, help_text='Date certificate was marked IN TRANSIT', null=True),
        ),
    ]
