# Generated by Django 2.0.4 on 2018-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0011_auto_20180426_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date_voided',
            field=models.DateField(blank=True, help_text='Date on which this certificate was voided', null=True),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='date_voided',
            field=models.DateField(blank=True, help_text='Date on which this certificate was voided', null=True),
        ),
    ]
