# Generated by Django 2.0.5 on 2018-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0012_auto_20180430_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='consignee',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='consignee_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_expiry',
            field=models.DateField(blank=True, help_text='60 from Date of Issue', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='harmonized_code',
            field=models.CharField(blank=True, choices=[('7102.10', '7102.10'), ('7102.21', '7102.21'), ('7102.31', '7102.31')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='consignee',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='consignee_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='date_of_expiry',
            field=models.DateField(blank=True, help_text='60 from Date of Issue', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='harmonized_code',
            field=models.CharField(blank=True, choices=[('7102.10', '7102.10'), ('7102.21', '7102.21'), ('7102.31', '7102.31')], max_length=32),
        ),
    ]
