# Generated by Django 2.0.5 on 2018-05-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0014_hscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='harmonized_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kpc.HSCode'),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='harmonized_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kpc.HSCode'),
        ),
    ]
