# Generated by Django 2.0.5 on 2018-05-10 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpc', '0015_auto_20180510_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_expiry', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Certificate Configuration',
                'verbose_name_plural': 'Certificate Configuration',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCertificateConfig',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('days_to_expiry', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Certificate Configuration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterModelOptions(
            name='hscode',
            options={'verbose_name': 'Harmonized System Code'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
