# Generated by Django 2.0.5 on 2018-05-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0017_auto_20180510_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hscode',
            options={'ordering': ['sort_order'], 'verbose_name': 'Harmonized System Code'},
        ),
        migrations.AlterModelOptions(
            name='voidreason',
            options={'ordering': ['sort_order']},
        ),
    ]
