# Generated by Django 2.0.5 on 2018-05-11 20:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpc', '0018_auto_20180510_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPortOfExport',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Port of Export',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='PortOfExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Port of Export',
                'verbose_name_plural': 'Ports of Export',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='hscode',
            options={'ordering': ['sort_order', 'value'], 'verbose_name': 'Harmonized System Code'},
        ),
        migrations.AlterModelOptions(
            name='voidreason',
            options={'ordering': ['sort_order', 'value']},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='aes',
            field=models.CharField(blank=True, help_text='AES Confirmation Number (ITN)', max_length=30, validators=[django.core.validators.RegexValidator(message='AES Confirmation (ITN) format is 14 digits prepended by X: X##############', regex='X\\d{14}')], verbose_name='AES'),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='aes',
            field=models.CharField(blank=True, help_text='AES Confirmation Number (ITN)', max_length=30, validators=[django.core.validators.RegexValidator(message='AES Confirmation (ITN) format is 14 digits prepended by X: X##############', regex='X\\d{14}')], verbose_name='AES'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='port_of_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kpc.PortOfExport'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='port_of_export',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kpc.PortOfExport'),
        ),
    ]
