# Generated by Django 2.0.5 on 2018-05-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0019_auto_20180511_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
