# Generated by Django 2.0.5 on 2018-05-15 14:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0020_auto_20180514_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateconfig',
            name='kp_countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Countries available for selection as Country of Origin', max_length=746, multiple=True, verbose_name='KP Countries'),
        ),
        migrations.AddField(
            model_name='historicalcertificateconfig',
            name='kp_countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Countries available for selection as Country of Origin', max_length=746, multiple=True, verbose_name='KP Countries'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True, verbose_name='Country of Origin'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_shipment',
            field=models.DateField(blank=True, help_text='Date certificate was marked SHIPPED', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True, verbose_name='Country of Origin'),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='date_of_shipment',
            field=models.DateField(blank=True, help_text='Date certificate was marked SHIPPED', null=True),
        ),
    ]
