# Generated by Django 2.0.5 on 2018-05-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0022_auto_20180515_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensee',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='historicallicensee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Licensee is active - able to request and access certificates'),
        ),
        migrations.AddField(
            model_name='licensee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Licensee is active - able to request and access certificates'),
        ),
    ]
