# Generated by Django 2.0.5 on 2018-05-21 15:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0023_auto_20180516_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpcAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='kpc.Licensee')),
            ],
            options={
                'ordering': ['licensee', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='kpcaddress',
            unique_together={('licensee', 'name')},
        ),
    ]
