# Generated by Django 2.0.5 on 2018-05-22 09:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpc', '0024_auto_20180521_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReceipt',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, default=1300)),
                ('licensee_name', models.CharField(max_length=256)),
                ('licensee_address', models.TextField()),
                ('certificates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certificates_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('date_sold', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical receipt',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1300, unique=True)),
                ('licensee_name', models.CharField(max_length=256)),
                ('licensee_address', models.TextField()),
                ('certificates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certificates_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('date_sold', models.DateField()),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
