# Generated by Django 2.0.5 on 2018-05-23 15:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kpc', '0025_historicalreceipt_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country of Origin'),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country of Origin'),
        ),
    ]
